catalogMode: strict
cleanupUnusedCatalogs: true
minimumReleaseAge: 4320
minimumReleaseAgeStrict: false
minimumReleaseAgeExclude:
  - '@fabdeh/*'
shellEmulator: true
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 43200 # 30 days
trustLockfile: true
blockExoticSubdeps: true
packages:
  - MyNetatmo24.EndToEndTests
  - MyNetatmo24.Frontend
allowBuilds:
  '@fabdeh/eslint-config': false
  '@parcel/watcher': false
  esbuild: false
  lmdb: false
  msgpackr-extract: false
  unrs-resolver: false

catalog:
  '@stoplight/spectral-cli': 6.16.0
  '@types/node': 24.13.2
  dotenv: 17.4.2
  jsdom: 29.1.1
  rxjs: ~7.8.2
  tslib: ^2.8.1
  typescript: ~6.0.3
  zod: ^4.3.5

catalogs:
  angular:
    '@analogjs/vite-plugin-angular': ^2.2.3
    '@angular/build': ^22.0.0
    '@angular/cdk': ^22.0.2
    '@angular/common': ^22.0.0
    '@angular/compiler': ^22.0.0
    '@angular/compiler-cli': ^22.0.0
    '@angular/core': ^22.0.0
    '@angular/forms': ^22.0.0
    '@angular/platform-browser': ^22.0.0
    '@angular/router': ^22.0.0
  eslint:
    '@fabdeh/eslint-config': ^0.12.1
    eslint: ^10.0.0
    eslint-plugin-better-tailwindcss: ^4.1.1
    eslint-plugin-erasable-syntax-only: ^0.4.0
    eslint-plugin-format: ^2.0.0
    eslint-plugin-playwright: ^2.7.1
  opentelemetry:
    '@opentelemetry/auto-instrumentations-web': 0.64.0
    '@opentelemetry/context-zone': 2.8.0
    '@opentelemetry/exporter-trace-otlp-http': 0.219.0
    '@opentelemetry/instrumentation': 0.219.0
    '@opentelemetry/resources': 2.8.0
    '@opentelemetry/sdk-trace-base': 2.8.0
    '@opentelemetry/sdk-trace-web': 2.8.0
    '@opentelemetry/semantic-conventions': 1.41.1
  playwright:
    '@playwright/test': 1.61.1
  spartanui:
    '@spartan-ng/brain': ^1.0.2
  tailwindcss:
    '@tailwindcss/vite': ^4.1.18
    '@tailwindplus/elements': ^1.0.22
    tailwindcss: ^4.1.12
  testing-library:
    '@testing-library/angular': 19.4.1
    '@testing-library/jest-dom': 6.9.1
    '@testing-library/user-event': 14.6.1
  vite:
    vite: ^8.0.0
  vitest:
    '@vitest/browser': 4.1.9
    '@vitest/browser-playwright': 4.1.9
    '@vitest/coverage-v8': 4.1.9
    '@vitest/ui': 4.1.9
    vitest: 4.1.9
