packages:
  - 'MyNetatmo24.Frontend'
#  - 'MyNetatmo24.EndToEndTests'

catalog:
  '@types/node': '24.10.7'
  'dotenv': '17.2.3'
  'jsdom': '27.4.0'
  'run-script-os': '1.1.6'
  'rxjs': '~7.8.2'
  'tslib': '^2.8.1'
  'typescript': '~5.9.3'
  'zod': '^4.3.5'

catalogs:
  angular:
    '@angular/build': '^21.1.2'
    '@angular/cli': '^21.1.2'
    '@angular/common': '^21.1.3'
    '@angular/compiler': '^21.1.3'
    '@angular/compiler-cli': '^21.1.3'
    '@angular/core': '^21.1.3'
    '@angular/forms': '^21.1.3'
    '@angular/platform-browser': '^21.1.3'
    '@angular/router': '^21.1.3'
    'ng-packagr': '^21.1.0'

  opentelemetry:
    '@opentelemetry/auto-instrumentations-web': '0.54.0'
    '@opentelemetry/context-zone': '2.3.0'
    '@opentelemetry/exporter-trace-otlp-proto': '0.209.0'
    '@opentelemetry/instrumentation': '0.209.0'
    '@opentelemetry/resources': '2.3.0'
    '@opentelemetry/sdk-trace-base': '2.3.0'
    '@opentelemetry/sdk-trace-web': '2.3.0'
    '@opentelemetry/semantic-conventions': '1.38.0'

  tailwindcss:
    '@tailwindcss/postcss': '^4.1.12'
    postcss: '^8.5.3'
    tailwindcss: '^4.1.12'

  testing-library:
    '@testing-library/angular': '19.0.0'
    '@testing-library/jest-dom': '6.9.1'
    '@testing-library/user-event': '14.6.1'

  eslint:
    '@fabdeh/eslint-config': '^0.9.0'
    'eslint': '^9.39.2'
    'eslint-plugin-better-tailwindcss': '^4.1.1'
    'eslint-plugin-erasable-syntax-only': '^0.4.0'
    'eslint-plugin-format': '^1.3.1'

  playwright:
    '@playwright/test': '1.57.0'
    'playwright': '1.57.0'

  vitest:
    '@vitest/browser': '4.0.17'
    '@vitest/browser-playwright': '4.0.17'
    '@vitest/coverage-v8': '4.0.17'
    '@vitest/ui': '4.0.17'
    'vitest': '4.0.17'
