packages:
  - MyNetatmo24.Frontend

catalog:
  '@types/node': 24.10.13
  dotenv: 17.3.1
  jsdom: 28.1.0
  rxjs: ~7.8.2
  tslib: ^2.8.1
  typescript: ~5.9.3
  zod: ^4.3.5

catalogs:
  angular:
    '@analogjs/vite-plugin-angular': ^2.2.3
    '@angular/common': ^21.1.3
    '@angular/compiler': ^21.1.3
    '@angular/core': ^21.1.3
    '@angular/forms': ^21.1.3
    '@angular/platform-browser': ^21.1.3
    '@angular/router': ^21.1.3
  eslint:
    '@fabdeh/eslint-config': ^0.9.0
    eslint: ^10.0.0
    eslint-plugin-better-tailwindcss: ^4.1.1
    eslint-plugin-erasable-syntax-only: ^0.4.0
    eslint-plugin-format: ^1.3.1
  opentelemetry:
    '@opentelemetry/auto-instrumentations-web': 0.57.0
    '@opentelemetry/context-zone': 2.5.1
    '@opentelemetry/exporter-trace-otlp-proto': 0.212.0
    '@opentelemetry/instrumentation': 0.212.0
    '@opentelemetry/resources': 2.5.1
    '@opentelemetry/sdk-trace-base': 2.5.1
    '@opentelemetry/sdk-trace-web': 2.5.1
    '@opentelemetry/semantic-conventions': 1.39.0
  playwright:
    '@playwright/test': 1.58.2
    playwright: 1.58.2
  tailwindcss:
    '@tailwindcss/vite': ^4.1.18
    daisyui: ^5.5.18
    tailwindcss: ^4.1.12
  testing-library:
    '@testing-library/angular': 19.1.0
    '@testing-library/jest-dom': 6.9.1
    '@testing-library/user-event': 14.6.1
  vite:
    vite: ^7.3.1
    vite-plugin-node-polyfills: ^0.25.0
    vite-tsconfig-paths: ^6.1.0
  vitest:
    '@vitest/browser': 4.0.18
    '@vitest/browser-playwright': 4.0.18
    '@vitest/coverage-v8': 4.0.18
    '@vitest/ui': 4.0.18
    vitest: 4.0.18
