// <auto-generated/>
#pragma warning disable CS0618
using ApiServiceSDK.Models.Microsoft.AspNetCore.Http;
using ApiServiceSDK.Models.Microsoft.AspNetCore.Mvc;
using ApiServiceSDK.Models.MyNetatmo24.Modules.AccountManagement.Application.Registration;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace ApiServiceSDK.Account.Register
{
    /// <summary>
    /// Builds and executes requests for operations under \account\register
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RegisterRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::ApiServiceSDK.Account.Register.RegisterRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RegisterRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/account/register", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ApiServiceSDK.Account.Register.RegisterRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RegisterRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/account/register", rawUrl)
        {
        }
        /// <summary>
        /// This endpoint creates the identity of a prospective user from their e-mail address, password and profile, and triggers the verification of their e-mail address. It creates no account: the account is provisioned on the first authenticated call. It requires no authentication. If the registration succeeds, a 204 No Content response is returned. If the submitted registration is invalid, or if the identity provider refuses the password as too weak, a 400 Bad Request response is returned. If the e-mail address is already registered, a 409 Conflict response is returned. If the identity provider is unavailable, a 502 Bad Gateway response is returned.
        /// </summary>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::ApiServiceSDK.Models.Microsoft.AspNetCore.Http.HttpValidationProblemDetails">When receiving a 400 status code</exception>
        /// <exception cref="global::ApiServiceSDK.Models.Microsoft.AspNetCore.Mvc.ProblemDetails">When receiving a 409 status code</exception>
        /// <exception cref="global::ApiServiceSDK.Models.Microsoft.AspNetCore.Mvc.ProblemDetails">When receiving a 502 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task PostAsync(global::ApiServiceSDK.Models.MyNetatmo24.Modules.AccountManagement.Application.Registration.RegistrationRequestDto body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task PostAsync(global::ApiServiceSDK.Models.MyNetatmo24.Modules.AccountManagement.Application.Registration.RegistrationRequestDto body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::ApiServiceSDK.Models.Microsoft.AspNetCore.Http.HttpValidationProblemDetails.CreateFromDiscriminatorValue },
                { "409", global::ApiServiceSDK.Models.Microsoft.AspNetCore.Mvc.ProblemDetails.CreateFromDiscriminatorValue },
                { "502", global::ApiServiceSDK.Models.Microsoft.AspNetCore.Mvc.ProblemDetails.CreateFromDiscriminatorValue },
            };
            await RequestAdapter.SendNoContentAsync(requestInfo, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// This endpoint creates the identity of a prospective user from their e-mail address, password and profile, and triggers the verification of their e-mail address. It creates no account: the account is provisioned on the first authenticated call. It requires no authentication. If the registration succeeds, a 204 No Content response is returned. If the submitted registration is invalid, or if the identity provider refuses the password as too weak, a 400 Bad Request response is returned. If the e-mail address is already registered, a 409 Conflict response is returned. If the identity provider is unavailable, a 502 Bad Gateway response is returned.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::ApiServiceSDK.Models.MyNetatmo24.Modules.AccountManagement.Application.Registration.RegistrationRequestDto body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::ApiServiceSDK.Models.MyNetatmo24.Modules.AccountManagement.Application.Registration.RegistrationRequestDto body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/problem+json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::ApiServiceSDK.Account.Register.RegisterRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::ApiServiceSDK.Account.Register.RegisterRequestBuilder WithUrl(string rawUrl)
        {
            return new global::ApiServiceSDK.Account.Register.RegisterRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class RegisterRequestBuilderPostRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
