// <auto-generated/>
#pragma warning disable CS0618
using ApiServiceSDK.Account.Ensure;
using ApiServiceSDK.Account.Me;
using ApiServiceSDK.Account.Restore;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace ApiServiceSDK.Account
{
    /// <summary>
    /// Builds and executes requests for operations under \account
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AccountRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The ensure property</summary>
        public global::ApiServiceSDK.Account.Ensure.EnsureRequestBuilder Ensure
        {
            get => new global::ApiServiceSDK.Account.Ensure.EnsureRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The me property</summary>
        public global::ApiServiceSDK.Account.Me.MeRequestBuilder Me
        {
            get => new global::ApiServiceSDK.Account.Me.MeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The restore property</summary>
        public global::ApiServiceSDK.Account.Restore.RestoreRequestBuilder Restore
        {
            get => new global::ApiServiceSDK.Account.Restore.RestoreRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ApiServiceSDK.Account.AccountRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AccountRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/account", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ApiServiceSDK.Account.AccountRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AccountRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/account", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
