// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace ApiServiceSDK.Models.MyNetatmo24.Modules.AccountManagement.Application.Registration
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class RegistrationRequestDto : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The URL of the avatar picture of the prospective user, which is optional. When present it must be an absolute https URL of at most 2048 characters.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AvatarUrl { get; set; }
#nullable restore
#else
        public string AvatarUrl { get; set; }
#endif
        /// <summary>The e-mail address of the prospective user, which is required and also acts as their login name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Email { get; set; }
#nullable restore
#else
        public string Email { get; set; }
#endif
        /// <summary>The family name of the prospective user, which is required. It is trimmed, must not be empty, must be at most 50 characters long and must contain no Unicode control or format character; every script is accepted.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FamilyName { get; set; }
#nullable restore
#else
        public string FamilyName { get; set; }
#endif
        /// <summary>The given name of the prospective user, which is required. It is trimmed, must not be empty, must be at most 50 characters long and must contain no Unicode control or format character; every script is accepted.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GivenName { get; set; }
#nullable restore
#else
        public string GivenName { get; set; }
#endif
        /// <summary>The display name chosen by the prospective user, which is required and is not unique. It is trimmed, must not be empty, must be at most 50 characters long and must contain no Unicode control or format character; every script is accepted.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Nickname { get; set; }
#nullable restore
#else
        public string Nickname { get; set; }
#endif
        /// <summary>The password chosen by the prospective user, which is required. Its strength is checked by the identity provider, not by this application.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Password { get; set; }
#nullable restore
#else
        public string Password { get; set; }
#endif
        /// <summary>A second copy of the password, which is required and must equal Password. It is collected so that a typo cannot silently lock the prospective user out of the identity they just created.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PasswordConfirmation { get; set; }
#nullable restore
#else
        public string PasswordConfirmation { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::ApiServiceSDK.Models.MyNetatmo24.Modules.AccountManagement.Application.Registration.RegistrationRequestDto"/> and sets the default values.
        /// </summary>
        public RegistrationRequestDto()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ApiServiceSDK.Models.MyNetatmo24.Modules.AccountManagement.Application.Registration.RegistrationRequestDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ApiServiceSDK.Models.MyNetatmo24.Modules.AccountManagement.Application.Registration.RegistrationRequestDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::ApiServiceSDK.Models.MyNetatmo24.Modules.AccountManagement.Application.Registration.RegistrationRequestDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "avatarUrl", n => { AvatarUrl = n.GetStringValue(); } },
                { "email", n => { Email = n.GetStringValue(); } },
                { "familyName", n => { FamilyName = n.GetStringValue(); } },
                { "givenName", n => { GivenName = n.GetStringValue(); } },
                { "nickname", n => { Nickname = n.GetStringValue(); } },
                { "password", n => { Password = n.GetStringValue(); } },
                { "passwordConfirmation", n => { PasswordConfirmation = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("avatarUrl", AvatarUrl);
            writer.WriteStringValue("email", Email);
            writer.WriteStringValue("familyName", FamilyName);
            writer.WriteStringValue("givenName", GivenName);
            writer.WriteStringValue("nickname", Nickname);
            writer.WriteStringValue("password", Password);
            writer.WriteStringValue("passwordConfirmation", PasswordConfirmation);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
